# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Default image command: FastAPI + Swagger/ReDoc + Streamable HTTP MCP at /mcp (agent-friendly).
# Stdio MCP: docker run ... python server.py --transport stdio
# Smithery overrides the container command with python server.py (see smithery.yaml).
FROM python:3.14-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    graphviz \
    curl \
    git \
    && rm -rf /var/lib/apt/lists/*

# requirements.txt includes `-e .`; install needs the project tree present.
COPY . .
RUN pip install --no-cache-dir -r requirements.txt

RUN mkdir -p /app/output

EXPOSE 8000

ENV FASTMCP_STATELESS_HTTP=true

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
