# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    graphviz \
    curl \
    git \
    && rm -rf /var/lib/apt/lists/*

# requirements.txt includes `-e .`; install needs the project tree present.
COPY . .
RUN pip install --no-cache-dir -r requirements.txt

RUN mkdir -p /app/output

EXPOSE 8000

# MCP stdio (default). For HTTP + REST + /mcp: uvicorn app:app --host 0.0.0.0 --port 8000
ENTRYPOINT ["python", "server.py", "--transport", "stdio"]
