{{- if and (include "uml-mcp.authEnabled" .) .Values.auth.secret.create (not .Values.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "uml-mcp.secretName" . }}
  labels:
    {{- include "uml-mcp.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- with .Values.auth.secret.proxyEncryptionKeys }}
  proxy-encryption-keys: {{ . | quote }}
  {{- end }}
  {{- with .Values.auth.secret.entraClientSecret }}
  entra-client-secret: {{ . | quote }}
  {{- end }}
{{- end }}
