"""A local Kroki with every companion, run by Docker Compose.

The compose file is generated (pip/uvx installs have no repository checkout) into
``$XDG_CONFIG_HOME/uml-mcp/kroki/compose.yml`` and started as the Compose project
``uml-mcp-kroki``. Kroki is published on the loopback interface only.

Commands run as argument lists (never through a shell) with timeouts.
"""

from __future__ import annotations

import json
import os
import shutil
import subprocess
from pathlib import Path
from typing import Any

PROJECT = "uml-mcp-kroki"
DEFAULT_PORT = 8001
IMAGES = {
    "kroki": "yuzutech/kroki",
    "mermaid": "yuzutech/kroki-mermaid",
    "blockdiag": "yuzutech/kroki-blockdiag",
    "bpmn": "yuzutech/kroki-bpmn",
    "excalidraw": "yuzutech/kroki-excalidraw",
}


class StackError(RuntimeError):
    """A docker compose command failed."""


class DockerUnavailable(StackError):
    """Docker (with the compose plugin) is not installed or not running."""


def url_for(port: int = DEFAULT_PORT) -> str:
    return f"http://127.0.0.1:{port}"


def compose_path() -> Path:
    xdg = os.environ.get("XDG_CONFIG_HOME") or str(Path.home() / ".config")
    return Path(xdg) / "uml-mcp" / "kroki" / "compose.yml"


def compose_yaml(port: int = DEFAULT_PORT) -> str:
    if not 1 <= port <= 65535:
        raise ValueError(f"invalid port: {port}")
    companions = "".join(
        f"  {name}:\n    image: {image}\n    restart: unless-stopped\n"
        for name, image in IMAGES.items()
        if name != "kroki"
    )
    return (
        "# Generated by `uml-mcp kroki up`; edits are overwritten.\n"
        "services:\n"
        "  kroki:\n"
        f"    image: {IMAGES['kroki']}\n"
        "    ports:\n"
        f'      - "127.0.0.1:{port}:8000"\n'
        "    environment:\n"
        "      KROKI_MERMAID_HOST: mermaid\n"
        "      KROKI_BLOCKDIAG_HOST: blockdiag\n"
        "      KROKI_BPMN_HOST: bpmn\n"
        "      KROKI_EXCALIDRAW_HOST: excalidraw\n"
        "    depends_on: [mermaid, blockdiag, bpmn, excalidraw]\n"
        "    restart: unless-stopped\n" + companions
    )


def docker_bin() -> str:
    path = shutil.which("docker")
    if not path:
        raise DockerUnavailable(
            "docker is not installed; see https://docs.docker.com/get-docker/"
        )
    return path


def _run(args: list[str], timeout: float = 120.0) -> subprocess.CompletedProcess:
    try:
        proc = subprocess.run(
            args, capture_output=True, text=True, timeout=timeout, check=False
        )
    except subprocess.TimeoutExpired as exc:
        raise StackError(f"timed out after {timeout:.0f}s: {' '.join(args)}") from exc
    except OSError as exc:
        raise DockerUnavailable(str(exc)) from exc
    return proc


def _compose(*args: str, timeout: float = 120.0) -> subprocess.CompletedProcess:
    cmd = [docker_bin(), "compose", "-p", PROJECT, "-f", str(compose_path()), *args]
    proc = _run(cmd, timeout)
    if proc.returncode != 0:
        detail = (proc.stderr or proc.stdout).strip().splitlines()
        message = detail[-1] if detail else f"exit code {proc.returncode}"
        if "Cannot connect to the Docker daemon" in (proc.stderr or ""):
            raise DockerUnavailable("the Docker daemon is not running")
        raise StackError(message)
    return proc


def docker_available() -> tuple[bool, str]:
    """(available, detail) for Docker and the compose plugin."""
    try:
        proc = _run([docker_bin(), "compose", "version"], timeout=20)
    except StackError as exc:
        return False, str(exc)
    if proc.returncode != 0:
        return False, (proc.stderr or "docker compose is not available").strip()
    daemon = _run([docker_bin(), "info", "--format", "{{.ServerVersion}}"], 20)
    if daemon.returncode != 0:
        return False, "the Docker daemon is not running"
    return True, f"Docker {daemon.stdout.strip()}"


def write_compose(port: int = DEFAULT_PORT) -> Path:
    path = compose_path()
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(compose_yaml(port), encoding="utf-8")
    return path


def configured_port() -> int | None:
    """Host port in the generated compose file, if there is one."""
    try:
        text = compose_path().read_text(encoding="utf-8")
    except OSError:
        return None
    for line in text.splitlines():
        line = line.strip().strip("-").strip().strip('"')
        if line.startswith("127.0.0.1:") and line.endswith(":8000"):
            return int(line.split(":")[1])
    return None


def up(port: int = DEFAULT_PORT, timeout: float = 900.0) -> dict[str, Any]:
    """Pull (first time) and start Kroki with all companions."""
    path = write_compose(port)
    _compose("up", "-d", "--remove-orphans", timeout=timeout)
    return {"url": url_for(port), "compose_file": str(path), "containers": ps()}


def down() -> dict[str, Any]:
    if not compose_path().exists():
        return {"stopped": False, "detail": "no stack was created"}
    _compose("down", "--remove-orphans", timeout=180)
    return {"stopped": True}


def ps() -> list[dict[str, Any]]:
    """Containers of the stack: service, state, status."""
    if not compose_path().exists():
        return []
    out = _compose("ps", "--all", "--format", "json", timeout=60).stdout.strip()
    if not out:
        return []
    try:
        rows = json.loads(out)
        rows = rows if isinstance(rows, list) else [rows]
    except ValueError:  # one JSON object per line (newer compose)
        rows = [json.loads(line) for line in out.splitlines() if line.strip()]
    return [
        {
            "service": r.get("Service"),
            "state": r.get("State"),
            "status": r.get("Status"),
            "image": r.get("Image"),
        }
        for r in rows
    ]


def logs(tail: int = 100) -> str:
    if not compose_path().exists():
        return ""
    return _compose("logs", "--no-color", "--tail", str(int(tail)), timeout=60).stdout


def status() -> dict[str, Any]:
    """Docker availability and the stack's containers (never raises)."""
    available, detail = docker_available()
    port = configured_port()
    info: dict[str, Any] = {
        "docker": available,
        "detail": detail,
        "compose_file": str(compose_path()),
        "url": url_for(port) if port else None,
        "containers": [],
        "command": "uml-mcp kroki up --use",
    }
    if available:
        try:
            info["containers"] = ps()
        except StackError as exc:
            info["detail"] = str(exc)
    return info


__all__ = [
    "DEFAULT_PORT",
    "IMAGES",
    "PROJECT",
    "DockerUnavailable",
    "StackError",
    "compose_path",
    "compose_yaml",
    "configured_port",
    "docker_available",
    "down",
    "logs",
    "ps",
    "status",
    "up",
    "url_for",
    "write_compose",
]
