#!/usr/bin/env python
"""Stage and pack the Claude Desktop MCPB bundle for UML-MCP.

The bundle is assembled from an explicit allowlist rather than by copying the
repository, so tests, docs, caches, logs, credentials and build output can never
leak into a published archive.

Usage::

    python scripts/build_mcpb.py                 # stage, lock, pack
    python scripts/build_mcpb.py --no-lock       # skip `uv lock` (offline)
    python scripts/build_mcpb.py --skip-pack     # stage only, no npx/mcpb
"""

from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
import tomllib
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
MANIFEST_SOURCE = ROOT / "packaging" / "mcpb" / "manifest.json"
MCPB_CLI = "@anthropic-ai/mcpb@2.1.2"

# Runtime packages copied into the bundle. Only these suffixes travel with them.
RUNTIME_PACKAGES = ("mcp_core", "tools")
PACKAGE_SUFFIXES = {".py", ".json", ".j2", ".txt", ".md"}
PACKAGE_SKIP_DIRS = {"__pycache__", ".pytest_cache", ".ruff_cache", ".mypy_cache"}

# Single files copied verbatim into the bundle root.
RUNTIME_FILES = ("server.py", "LICENSE")

# Defense in depth: running the bundle in place (a smoke test, or Claude Desktop
# itself) creates .venv/ and logs/ next to the manifest. `mcpb pack` honours this
# file, so a pack over a previously-run stage still produces a clean archive.
MCPBIGNORE = """.venv/
logs/
output/
__pycache__/
*.pyc
*.log
"""

# A staged tree containing any of these is a build failure, not a warning.
FORBIDDEN_NAMES = {
    ".env",
    ".git",
    ".github",
    ".venv",
    "docs",
    "examples",
    "htmlcov",
    "logs",
    "output",
    "site",
    "tests",
}
FORBIDDEN_SUFFIXES = {".pyc", ".pyo", ".log", ".pdf", ".coverage", ".mcpb"}


def load_pyproject() -> dict[str, Any]:
    return tomllib.loads((ROOT / "pyproject.toml").read_text(encoding="utf-8"))


def render_manifest(version: str) -> dict[str, Any]:
    """Load the checked-in manifest and stamp it with the pyproject version."""
    manifest = json.loads(MANIFEST_SOURCE.read_text(encoding="utf-8"))
    manifest["version"] = version
    return manifest


def build_bundle_pyproject(pyproject: dict[str, Any]) -> str:
    """Generate the bundle's pyproject from the repository's own metadata.

    Dependencies and the Python floor are copied verbatim so the bundle can never
    drift from the project. ``package = false`` keeps ``uv`` from building
    UML-MCP itself: the bundle ships the packages and only needs their
    dependencies resolved into a virtualenv.
    """
    project = pyproject["project"]
    dependencies = "".join(f'    "{dep}",\n' for dep in project["dependencies"])
    return (
        "# Generated by scripts/build_mcpb.py. Do not edit.\n"
        "[project]\n"
        f'name = "{project["name"]}"\n'
        f'version = "{project["version"]}"\n'
        f'description = "{project["description"]}"\n'
        f'requires-python = "{project["requires-python"]}"\n'
        "dependencies = [\n"
        f"{dependencies}"
        "]\n"
        "\n"
        "[tool.uv]\n"
        "package = false\n"
    )


def copy_package(source: Path, destination: Path) -> None:
    for path in sorted(source.rglob("*")):
        if any(part in PACKAGE_SKIP_DIRS for part in path.parts):
            continue
        if path.is_dir():
            continue
        if path.suffix not in PACKAGE_SUFFIXES:
            continue
        target = destination / path.relative_to(source)
        target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(path, target)


def stage(stage_dir: Path, pyproject: dict[str, Any]) -> None:
    if stage_dir.exists():
        shutil.rmtree(stage_dir)
    stage_dir.mkdir(parents=True)

    version = pyproject["project"]["version"]
    (stage_dir / "manifest.json").write_text(
        json.dumps(render_manifest(version), indent=2) + "\n", encoding="utf-8"
    )
    (stage_dir / "pyproject.toml").write_text(
        build_bundle_pyproject(pyproject), encoding="utf-8"
    )
    (stage_dir / ".mcpbignore").write_text(MCPBIGNORE, encoding="utf-8")

    for name in RUNTIME_FILES:
        shutil.copy2(ROOT / name, stage_dir / name)

    for package in RUNTIME_PACKAGES:
        copy_package(ROOT / package, stage_dir / package)

    icon = MANIFEST_SOURCE.parent / "icon.png"
    if icon.exists():
        shutil.copy2(icon, stage_dir / "icon.png")


def _is_forbidden(relative: Path, is_file: bool) -> bool:
    if any(part in FORBIDDEN_NAMES for part in relative.parts):
        return True
    if not is_file:
        return False
    return relative.suffix in FORBIDDEN_SUFFIXES or relative.name.startswith(".env")


def audit(stage_dir: Path) -> list[str]:
    """Return staged paths that must never ship. Empty list means clean."""
    offenders: list[str] = []
    for path in sorted(stage_dir.rglob("*")):
        relative = path.relative_to(stage_dir)
        if _is_forbidden(relative, path.is_file()):
            offenders.append(str(relative))
    return offenders


def run(command: list[str], cwd: Path | None = None) -> None:
    print(f"$ {' '.join(command)}", flush=True)
    subprocess.run(command, cwd=cwd, check=True)


def npx(args: list[str]) -> list[str]:
    executable = shutil.which("npx") or "npx"
    return [executable, "-y", MCPB_CLI, *args]


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--out", default="dist", help="Output directory (default: dist)"
    )
    parser.add_argument(
        "--no-lock",
        action="store_true",
        help="Skip `uv lock`; the bundle then resolves dependencies on first launch",
    )
    parser.add_argument(
        "--skip-pack",
        action="store_true",
        help="Stage and audit only; do not invoke the mcpb CLI",
    )
    args = parser.parse_args(argv)

    pyproject = load_pyproject()
    version = pyproject["project"]["version"]

    declared = json.loads(MANIFEST_SOURCE.read_text(encoding="utf-8"))["version"]
    if declared != version:
        print(
            f"warning: {MANIFEST_SOURCE.name} declares {declared} but pyproject is "
            f"{version}; staging {version}",
            file=sys.stderr,
        )

    out_dir = (
        (ROOT / args.out).resolve()
        if not Path(args.out).is_absolute()
        else Path(args.out)
    )
    stage_dir = out_dir / "mcpb-stage"
    out_dir.mkdir(parents=True, exist_ok=True)

    stage(stage_dir, pyproject)
    print(f"staged {stage_dir}")

    offenders = audit(stage_dir)
    if offenders:
        print("FAIL: staged bundle contains excluded paths:", file=sys.stderr)
        for offender in offenders:
            print(f"  - {offender}", file=sys.stderr)
        return 1

    if not args.no_lock:
        run(["uv", "lock", "--directory", str(stage_dir)])

    if args.skip_pack:
        print("staging complete (--skip-pack)")
        return 0

    bundle = out_dir / f"uml-mcp-{version}.mcpb"
    run(npx(["validate", str(stage_dir / "manifest.json")]))
    run(npx(["pack", str(stage_dir), str(bundle)]))
    print(f"built {bundle}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
